### ISSUE TITLE
Tried to access visual service WindowManager from a non-visual Context

### ISSUE THREAD

**Issue by joaoeudes7** [PostHog/posthog-android#14]
This error happens when start the service of posthog

```
Tried to access visual service WindowManager from a non-visual Context:id.app.App@9b44ad0 WindowManager should be accessed from Activity or other visual Context. 
Use an Activity or a Context created with Context#createWindowContext(int, Bundle), which are adjusted to the configuration and visual bounds of an area on screen.
java.lang.IllegalAccessException: Tried to access visual service WindowManager from a non-visual Context:id.app.App@9b44ad0
at android.app.ContextImpl.getSystemService(ContextImpl.java:2070)
at android.content.ContextWrapper.getSystemService(ContextWrapper.java:869)
at com.posthog.android.internal.Utils.getSystemService(Utils.java:153)
at com.posthog.android.PostHogContext.putScreen(PostHogContext.java:251)
at com.posthog.android.PostHogContext.create(PostHogContext.java:132)
at com.posthog.android.PostHog$Builder.build(PostHog.java:1015)
at id.app.data.services.trackers.PostHogTrackerService.startService(PostHogTrackerService.kt:19)
at id.app.App.startTrackerService(App.kt:63)
at id.app.App.onCreate(App.kt:56)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1225)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7069)
at android.app.ActivityThread.access$1800(ActivityThread.java:258)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2207)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:233)
at android.os.Looper.loop(Looper.java:344)
at android.app.ActivityThread.main(ActivityThread.java:8204)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071).
```

This error happens same when use the context from Activity

**Comment by marandaneto** [comment]
We're currently reworking the Android SDK and not using the `WindowManager` to retrieve the screen's metadata, so this issue should be gone altogether.
Will move this to WIP, stay tuned.

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog-android/releases/tag/3.0.0-alpha.4 fixes this by not using the `WindowManager` directly.
Also, we always use the App context from the Activity context, we don't require the Activity context for anything since this may cause leaks anyway.
