### ISSUE TITLE
Preconditions.outOfBounds Random Crash 

### ISSUE THREAD

**Issue by LuisBruno1** [PostHog/posthog-android#183]
### Version

posthog-android:3.6.1

### Steps to Reproduce

Recently, our team has been testing PostHog, and we are receiving crash reports from Firebase Crashlytics. The crash appears to be random because it happens in different sections of the app once the recording has started. The logs don't provide us with any context about the issue. I have searched for solutions to this problem, but I was unsuccessful.

### Expected Result

I'm starting the session replay recording with the following code. Is there anything I can change to prevent the crash?

```
val config = PostHogAndroidConfig(
        apiKey = POSTHOG_API_KEY,
        host = POSTHOG_HOST,
        sessionReplayConfig = PostHogSessionReplayConfig(maskAllImages = false, maskAllTextInputs = false, captureLogcat = true, screenshot = true)
    ).apply {
        sessionReplay = true
    }
    fitiaAnalyticManager.setStartRecordingPostHog()
    PostHogAndroid.setup(context, config)
```

### Actual Result

 Fatal Exception: java.lang.IndexOutOfBoundsException: Index 5 out of bounds for length 0
       at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
       at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
       at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
       at java.util.Objects.checkIndex(Objects.java:359)
       at java.util.ArrayList.get(ArrayList.java:434)
       at android.view.ViewGroup.populateChildrenForAutofill(ViewGroup.java:3946)
       at android.view.ViewGroup.populateChildrenForAutofill(ViewGroup.java:3956)
       at android.view.ViewGroup.populateChildrenForAutofill(ViewGroup.java:3956)
       at android.view.ViewGroup.getChildrenForAutofill(ViewGroup.java:3915)
       at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3879)
       at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3885)
       at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:528)
       at android.app.assist.AssistStructure.<init>(AssistStructure.java:2360)
       at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:4409)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2638)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by marandaneto** [comment]
Looks like similar to this one https://github.com/PostHog/posthog-android/issues/161
What does the method `fitiaAnalyticManager.setStartRecordingPostHog()` do?
I would need some reproducible steps or sample app, see [comment](https://github.com/PostHog/posthog-android/issues/161#issuecomment-2360657786) since I tried with different devices, different versions, etc, and I never managed to reproduce the issue by myself

**Comment by icksannugrahaa** [comment]
Version
posthog-android:3.5.0
posthog-android:3.7.4

Steps to Reproduce
1. Integrate the SDK.
2. Enable sessionReplay in the config.
3. Launch the app.
4. Just do scroll or do nothing in app.
5. App crashes.
6. If i set sessionReplay to false, my app work normaly.

Expected Result
how to prevent the crash?

config code : 
`
val config = PostHogAndroidConfig(
                apiKey = POSTHOG_API_KEY,
                host = POSTHOG_HOST
            ).apply {
                sessionReplay = true
                debug = true
                sessionReplayConfig = PostHogSessionReplayConfig(
                    maskAllTextInputs = false,
                    maskAllImages = true,
                    screenshot = false
                )
            }
            PostHogAndroid.setup(this, config)
            
`
            
Actual Result

`
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
                                                                                                    	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
                                                                                                    	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
                                                                                                    	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
                                                                                                    	at java.util.Objects.checkIndex(Objects.java:359)
                                                                                                    	at java.util.ArrayList.get(ArrayList.java:434)
                                                                                                    	at android.view.ViewGroup.onInitializeAccessibilityNodeInfoInternal(ViewGroup.java:3841)
                                                                                                    	at android.view.View.onInitializeAccessibilityNodeInfo(View.java:9232)
                                                                                                    	at android.view.View.createAccessibilityNodeInfoInternal(View.java:9191)
                                                                                                    	at android.view.View.createAccessibilityNodeInfo(View.java:9176)
                                                                                                    	at android.view.AccessibilityInteractionController.populateAccessibilityNodeInfoForView(AccessibilityInteractionController.java:429)
                                                                                                    	at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:372)
                                                                                                    	at android.view.AccessibilityInteractionController.-$$Nest$mfindAccessibilityNodeInfoByAccessibilityIdUiThread(Unknown Source:0)
                                                                                                    	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1719)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8592)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
`
PostHog log : 

`
2024-09-24 14:14:44.026  5906-6048  PostHog                 D  Queued Event $snapshot: 019222e1-eab7-7645-b813-6daefd024a60.event.
2024-09-24 14:14:44.026  5906-6048  PostHog                 D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:44.541  5906-6048  PostHog                 D  Queued Event $snapshot: 019222e1-ecba-7596-8282-f37769d94e53.event.
2024-09-24 14:14:44.541  5906-6048  PostHog                 D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:47.485  5906-6048  PostHog                 D  Queued Event $snapshot: 019222e1-f83c-7aa3-8c21-8a990de60ccc.event.
2024-09-24 14:14:47.485  5906-6048  PostHog                D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:50.225  5906-6048  PostHog                  D  Queued Event $snapshot: 019222e2-02ef-729c-b8fd-736bf041cca8.event.
2024-09-24 14:14:50.225  5906-6048  PostHog                 D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:50.729  5906-6048  PostHog                 D  Queued Event $snapshot: 019222e2-04e7-79f1-840f-21e53577e9aa.event.
2024-09-24 14:14:50.729  5906-6048  PostHog                 D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:54.496  5906-6015  PostHog                  D  Cannot flush the Queue yet, below the threshold: 1
2024-09-24 14:14:56.080  5906-6048  PostHog                 D  Queued Event $snapshot: 019222e2-19cd-7b27-973f-ea1de9f7a2a1.event.
2024-09-24 14:14:56.080  5906-6048  PostHog                D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:56.195  5906-6048  PostHog                 D  Queued Event $snapshot: 019222e2-1a42-7d01-bfec-bb2a9824d402.event.
2024-09-24 14:14:56.195  5906-6048  PostHog                 D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:56.421  5906-6048  PostHog                 D  Queued Event $snapshot: 019222e2-1b16-78f3-af6d-eda2935db64b.event.
2024-09-24 14:14:56.421  5906-6048  PostHog                 D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:56.953  5906-6048  PostHog                 D  Queued Event $snapshot: 019222e2-1d31-7d05-96c9-eadd8464c5e3.event.
2024-09-24 14:14:56.953  5906-6048  PostHog                 D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:57.451  5906-6048  PostHog                 D  Queued Event $snapshot: 019222e2-1f29-74fe-9c11-909f8f288260.event.
2024-09-24 14:14:57.451  5906-6048  PostHog                 D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:57.453  5906-6048  PostHog                 D  Queued Event $snapshot: 019222e2-1f2d-744b-8b57-264700d6730d.event.
2024-09-24 14:14:57.453  5906-6048  PostHog                 D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:57.595  5906-6048  PostHog                 D  Queued Event $snapshot: 019222e2-1fb9-7ab2-a31f-f8b1e8f9772f.event.
2024-09-24 14:14:57.595  5906-6048  PostHog                  D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:58.030  5906-6048  PostHog                 D  Queued Event $snapshot: 019222e2-2149-7ff0-be73-55af7b321cf4.event.
2024-09-24 14:14:58.030  5906-6048  PostHog                 D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:58.223  5906-6048  PostHog                 D  Queued Event $snapshot: 019222e2-222e-78d0-af2b-8212e6617059.event.
2024-09-24 14:14:58.223  5906-6048  PostHog                 D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:58.397  5906-6048  PostHog                 D  Queued Event $snapshot: 019222e2-22dc-7c6c-9e45-0ebb42a4987e.event.
2024-09-24 14:14:58.397  5906-6048  PostHog                 D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:58.546  5906-6048  PostHog                  D  Queued Event $snapshot: 019222e2-2366-7687-ad99-a94b4d131adb.event.
2024-09-24 14:14:58.546  5906-6048  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:14:59.021  5906-6048  PostHog                          D  Queued Event $snapshot: 019222e2-253e-78e1-aa25-86083f305cc0.event.
2024-09-24 14:14:59.021  5906-6048  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:00.024  5906-6048  PostHog                          D  Queued Event $snapshot: 019222e2-2937-7754-b9c3-bfa63e077814.event.
2024-09-24 14:15:00.024  5906-6048  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:00.024  5906-6048  PostHog                          D  Queued Event $snapshot: 019222e2-2937-7754-b9c3-bfa63e077815.event.
2024-09-24 14:15:00.024  5906-6048  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:00.024  5906-6048  PostHog                          D  Queued Event $snapshot: 019222e2-2937-7754-b9c3-bfa63e077816.event.
2024-09-24 14:15:00.072  5906-6048  PostHog                          D  Flushing 20 events.
2024-09-24 14:15:00.476  7645-7765  PostHog                 pid-7645                             D  Queued Event $snapshot: 019222e2-2aef-7562-9da4-bede3d1ffea4.event.
2024-09-24 14:15:00.476  7645-7765  PostHog                 pid-7645                             D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:00.477  7645-7765  PostHog                 pid-7645                             D  Queued Event $snapshot: 019222e2-2aef-7562-9da4-bede3d1ffea5.event.
2024-09-24 14:15:00.477  7645-7765  PostHog                 pid-7645                             D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:00.477  7645-7765  PostHog                 pid-7645                             D  Queued Event $snapshot: 019222e2-2af0-78c8-933c-09ab2bddd1c0.event.
2024-09-24 14:15:00.477  7645-7765  PostHog                 pid-7645                             D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:00.477  7645-7765  PostHog                 pid-7645                             D  Queued Event $snapshot: 019222e2-2af0-78c8-933c-09ab2bddd1c1.event.
2024-09-24 14:15:00.477  7645-7765  PostHog                 pid-7645                             D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:00.478  7645-7765  PostHog                 pid-7645                             D  Queued Event $snapshot: 019222e2-2af0-78c8-933c-09ab2bddd1c2.event.
2024-09-24 14:15:00.478  7645-7765  PostHog                 pid-7645                             D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:00.478  7645-7765  PostHog                 pid-7645                             D  Queued Event $snapshot: 019222e2-2af0-78c8-933c-09ab2bddd1c3.event.
2024-09-24 14:15:00.478  7645-7765  PostHog                 pid-7645                             D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:00.479  7645-7765  PostHog                 pid-7645                             D  Queued Event $snapshot: 019222e2-2af0-78c8-933c-09ab2bddd1c4.event.
2024-09-24 14:15:00.479  7645-7765  PostHog                 pid-7645                             D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:00.479  7645-7765  PostHog                 pid-7645                             D  Queued Event $snapshot: 019222e2-2af0-78c8-933c-09ab2bddd1c5.event.
2024-09-24 14:15:00.479  7645-7765  PostHog                 pid-7645                             D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:00.479  7645-7765  PostHog                 pid-7645                             D  Queued Event $snapshot: 019222e2-2af0-78c8-933c-09ab2bddd1c6.event.
2024-09-24 14:15:00.479  7645-7765  PostHog                 pid-7645                             D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:00.480  7645-7765  PostHog                 pid-7645                             D  Queued Event $snapshot: 019222e2-2af0-78c8-933c-09ab2bddd1c7.event.
2024-09-24 14:15:00.480  7645-7765  PostHog                 pid-7645                             D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:00.480  7645-7765  PostHog                 pid-7645                             D  Queued Event $snapshot: 019222e2-2af1-7f16-83c3-5b35755eb903.event.
2024-09-24 14:15:00.480  7645-7765  PostHog                 pid-7645                             D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:00.480  7645-7765  PostHog                 pid-7645                             D  Queued Event $snapshot: 019222e2-2af1-7f16-83c3-5b35755eb904.event.
2024-09-24 14:15:00.480  7645-7765  PostHog                 pid-7645                             D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:00.480  7645-7765  PostHog                 pid-7645                             D  Queued Event $snapshot: 019222e2-2af1-7f16-83c3-5b35755eb905.event.
2024-09-24 14:15:00.487  7645-7765  PostHog                 pid-7645                             D  Flushing 20 events.
2024-09-24 14:15:00.587  7645-7797  PostHog                 pid-7645                             D  Queued Event $screen: 019222e2-2b69-7a90-95fd-1944a6d4c3cc.event.
2024-09-24 14:15:00.587  7645-7797  PostHog                 pid-7645                             D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.240  7645-7765  PostHog                          D  Flushed 20 events successfully.
2024-09-24 14:15:02.243  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2af1-7f16-83c3-5b35755eb906.event.
2024-09-24 14:15:02.243  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.244  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2af1-7f16-83c3-5b35755eb907.event.
2024-09-24 14:15:02.244  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.245  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2af1-7f16-83c3-5b35755eb908.event.
2024-09-24 14:15:02.245  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.246  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2afd-7278-910c-0429b8303480.event.
2024-09-24 14:15:02.246  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.247  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b07-7609-a9e6-c6f0ad26359b.event.
2024-09-24 14:15:02.247  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.247  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b07-7609-a9e6-c6f0ad26359c.event.
2024-09-24 14:15:02.247  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.248  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b16-7965-a324-83a24d219702.event.
2024-09-24 14:15:02.248  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.248  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b30-7695-84f7-7ff291337e49.event.
2024-09-24 14:15:02.248  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.249  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b30-7695-84f7-7ff291337e4a.event.
2024-09-24 14:15:02.249  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.250  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b30-7695-84f7-7ff291337e4b.event.
2024-09-24 14:15:02.250  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.250  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b31-70b0-9af9-4a25c8c45d98.event.
2024-09-24 14:15:02.250  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.251  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b31-70b0-9af9-4a25c8c45d99.event.
2024-09-24 14:15:02.251  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.252  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b31-70b0-9af9-4a25c8c45d9a.event.
2024-09-24 14:15:02.252  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.252  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b31-70b0-9af9-4a25c8c45d9b.event.
2024-09-24 14:15:02.253  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.253  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b31-70b0-9af9-4a25c8c45d9c.event.
2024-09-24 14:15:02.253  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.254  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b31-70b0-9af9-4a25c8c45d9d.event.
2024-09-24 14:15:02.254  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.255  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b31-70b0-9af9-4a25c8c45d9e.event.
2024-09-24 14:15:02.255  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.256  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b31-70b0-9af9-4a25c8c45d9f.event.
2024-09-24 14:15:02.256  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.257  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b31-70b0-9af9-4a25c8c45da0.event.
2024-09-24 14:15:02.257  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:02.258  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b31-70b0-9af9-4a25c8c45da1.event.
2024-09-24 14:15:02.271  7645-7765  PostHog                          D  Flushing 20 events.
2024-09-24 14:15:03.575  7645-7765  PostHog                          D  Flushed 20 events successfully.
2024-09-24 14:15:03.581  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b31-70b0-9af9-4a25c8c45da2.event.
2024-09-24 14:15:03.581  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.581  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b32-78d3-ac5d-a424685a97ec.event.
2024-09-24 14:15:03.581  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.582  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b32-78d3-ac5d-a424685a97ed.event.
2024-09-24 14:15:03.582  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.582  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b32-78d3-ac5d-a424685a97ee.event.
2024-09-24 14:15:03.582  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.582  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b32-78d3-ac5d-a424685a97ef.event.
2024-09-24 14:15:03.582  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.583  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b32-78d3-ac5d-a424685a97f0.event.
2024-09-24 14:15:03.583  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.583  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b32-78d3-ac5d-a424685a97f1.event.
2024-09-24 14:15:03.584  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.584  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b32-78d3-ac5d-a424685a97f2.event.
2024-09-24 14:15:03.584  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.585  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b32-78d3-ac5d-a424685a97f3.event.
2024-09-24 14:15:03.585  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.586  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b32-78d3-ac5d-a424685a97f4.event.
2024-09-24 14:15:03.586  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.587  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b32-78d3-ac5d-a424685a97f5.event.
2024-09-24 14:15:03.587  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.587  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b32-78d3-ac5d-a424685a97f6.event.
2024-09-24 14:15:03.587  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.588  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b33-75e9-bbee-2ca1e7829f73.event.
2024-09-24 14:15:03.588  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.588  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b33-75e9-bbee-2ca1e7829f74.event.
2024-09-24 14:15:03.588  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.589  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b33-75e9-bbee-2ca1e7829f75.event.
2024-09-24 14:15:03.589  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.589  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2b70-7aa2-a070-58426be52e0d.event.
2024-09-24 14:15:03.589  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.589  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2bd9-7a11-981e-019176eab196.event.
2024-09-24 14:15:03.589  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.590  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2bd9-7a11-981e-019176eab197.event.
2024-09-24 14:15:03.590  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.591  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2bd9-7a11-981e-019176eab198.event.
2024-09-24 14:15:03.591  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:03.591  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2bea-7eab-a405-032cb39d25bc.event.
2024-09-24 14:15:03.598  7645-7765  PostHog                          D  Flushing 20 events.
2024-09-24 14:15:04.496  7645-7765  PostHog                          D  Flushed 20 events successfully.
2024-09-24 14:15:04.501  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2cab-70ea-bb8b-7359f5394ff7.event.
2024-09-24 14:15:04.501  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:04.502  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2cb0-7d63-ac6d-a9cc1e4743f5.event.
2024-09-24 14:15:04.502  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:04.503  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2db0-79d6-b8af-0943226d1102.event.
2024-09-24 14:15:04.503  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:04.504  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2dbe-7934-85f2-c10176ac87b5.event.
2024-09-24 14:15:04.504  7645-7765  PostHog                          D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:04.509  7645-7765  PostHog                          D  Queued Event $snapshot: 019222e2-2dd8-77c4-a484-ee595a38578e.event.
2024-09-24 14:15:04.509  7645-7765  PostHog                 D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:04.510  7645-7765  PostHog                 D  Queued Event $snapshot: 019222e2-2fed-7111-99a7-50e6d3ea4dec.event.
2024-09-24 14:15:04.510  7645-7765  PostHog                 D  Cannot flush the Queue yet, below the threshold: 20
2024-09-24 14:15:30.421  7645-7797  PostHog                 D  Flushing 1 events.
2024-09-24 14:15:30.812  7645-7797  PostHog                 D  Flushed 1 events successfully.

`

**Comment by marandaneto** [comment]
@icksannugrahaa can you provide a minimal reproducible example? a sample app that crashes the app using PostHog? this is the only alternative I have right now since I tried many times.
Also which device are you testing this, which OS version, etc.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
