### ISSUE TITLE
ConcurrentModificationException Crash Immediately after initializing PostHog

### ISSUE THREAD

**Issue by ubeyou** [PostHog/posthog-android#212]
### Version

3+

### Steps to Reproduce

I have initialize posthog 3+ in the App.kt

```
val config = PostHogAndroidConfig(
            apiKey = POSTHOG_API_KEY,
            host = POSTHOG_HOST
        )
        PostHogAndroid.setup(this, config)
```
        
Then I'm getting Crash and I can't login anymore.

 java.util.ConcurrentModificationException
                                                                                                    	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1111)
                                                                                                    	at java.util.ArrayList$Itr.next(ArrayList.java:1064)
                                                                                                    	at com.cisco.android.common.utils.extensions.ListExtKt.a(Unknown Source:25)
                                                                                                    	at com.cisco.android.common.utils.RootViewObserver.access$injectObserverIfNeeded(SourceFile:1)
                                                                                                    	at com.cisco.android.common.utils.RootViewObserver$c.doFrame(Unknown Source:9)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1592)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1603)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1125)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:1026)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1567)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:224)
                                                                                                    	at android.os.Looper.loop(Looper.java:318)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8790)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

### Expected Result

Able to access the app

### Actual Result

App crash on start. After removing the PostHog Init, it works again. Was updating from PostHog 1 to PostHog 3 earlier.

**Comment by ubeyou** [comment]
Just to update

When I downgraded to 3.0.0, no crashes, if i put any version >= 3.1.0, there will be crash on start.

**Comment by marandaneto** [comment]
@ubeyou I wonder if its conflicting with any dependencies.
As you can see in the stack trace, you see `com.cisco.android`, this is not part of our SDK.

Can you add a breakpoint to somewhere here:

> java.util.ConcurrentModificationException
> at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1111)
> at java.util.ArrayList$Itr.next(ArrayList.java:1064)
> at com.cisco.android.common.utils.extensions.ListExtKt.a(Unknown Source:25)
> at com.cisco.android.common.utils.RootViewObserver.access$injectObserverIfNeeded(SourceFile:1)
> at com.cisco.android.common.utils.RootViewObserver$c.doFrame(Unknown Source:9)

And see where this is happening? Thanks

**Comment by marandaneto** [comment]
@ubeyou any more context?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
