### ISSUE TITLE
Crash with recordScreenViews()

### ISSUE THREAD

**Issue by ferinagy** [PostHog/posthog-android#26]
Version used: 2.0.3

When enabling the screen view recording, we encountered the following crash:

```
FATAL EXCEPTION: main
Process: at.beeone.george.dev, PID: 2802
java.lang.IllegalArgumentException: name must be provided.
	at com.posthog.android.PostHog.screen(PostHog.java:523)
	at com.posthog.android.PostHog.screen(PostHog.java:501)
	at com.posthog.android.PostHog.recordScreenViews(PostHog.java:316)
	at com.posthog.android.PostHogActivityLifecycleCallbacks.onActivityStarted(PostHogActivityLifecycleCallbacks.java:106)
	at android.app.Application.dispatchActivityStarted(Application.java:421)
	at android.app.Activity.dispatchActivityStarted(Activity.java:1407)
	at android.app.Activity.onStart(Activity.java:1948)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:345)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
        ...
```
We have some activities that deliberately set `android:label=""` to avoid being read by screen reader that are probably causing this. The sdk should not crash. Either not tracking the event or tracking the activity class name instead would be better.

**Comment by marandaneto** [comment]
We're currently reworking the Android SDK and this will be taken care of, will move this to WIP, so stay tuned.

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog-android/pull/32 should address this use case.
